server:
  port: 8000

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: sample-service
          uri: lb://SAMPLE-SERVICE  # 포워딩 주소. 로드밸런싱 처리
          predicates:
            - Path=/sample/**
          filters:            
            - RewritePath=/sample/(?<segment>.*), /$\{segment}  # java application의 /user prefix 생략            

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<segment>.*), /$\{segment}      
            
        - id: delivery-service
          uri: lb://DELIVERY-SERVICE
          predicates:
            - Path=/delivery/**
          filters:
            - RewritePath=/delivery/(?<segment>.*), /$\{segment}   
        
        - id: team-service
          uri: lb://TEAM-SERVICE
          predicates:
            - Path=/team/**
          filters:
            - RewritePath=/team/(?<segment>.*), /$\{segment}  
        
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
          filters:
            - RewritePath=/order/(?<segment>.*), /$\{segment}  

        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member/**
          filters:
            - RewritePath=/member/(?<segment>.*), /$\{segment}    
        
        - id: board-service
          uri: lb://BOARD-SERVICE
          predicates:
            - Path=/board/**
          filters:
            - RewritePath=/board/(?<segment>.*), /$\{segment}           

        - id: sample-maven
          uri: lb://SAMPLE-MAVEN  # 포워딩 주소. 로드밸런싱 처리
          predicates:
            - Path=/sample-maven/**
          filters:            
            - RewritePath=/sample-maven/(?<segment>.*), /$\{segment}  # java application의 /user prefix 생략            
 
      discovery:
        locator:
          enabled: true

# config server actuator
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info

eureka:
  client:
    register-with-eureka: true # eureka 서버에 등록
    fetch-registry: true # 외부 검색 가능
    service-url:
      defaultZone: http://admin:admin@${eureka.instance.hostname:localhost}:8761/eureka

info:
  app:
    name: Spring Cloud Gateway
    description: API 라우팅 및 보안, 모니터링/메트릭 등의 기능을 간단하고 효과적인 방법으로 제공
  swagger-ui: http://localhost:8000/webjars/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config

messages:
  directory: ${user.dir}/msa-attach-volume/messages
