server:
  port: 8888

spring:
  application:
    name: config-service    
  config:    
    use-legacy-processing: true
  profiles:
    active: native, test
  cloud:
    config:
      server:
        native:
         search-locations: file:///${user.home}/workspace/cloud-sample-config # Windows
#      search-locations: file://${user.home}/workspace/cloud-sample-config # MacOS, linux
#     search-locations: classpath:/server-configs # local folder

management:
  endpoints:
    web:
      exposure:
        include: health, beans, refresh # health : 현재 상태 확인 가능, refresh : 애플리케이션 설정 값들을 빌드와 배포 없이 다시 받음 단 POST 요청