spring:
    devtools:   
      livereload:
        enabled: true # 정적 리소스에 변화가 있을 떄 바로 반영

    # thymeleaf 참조 경로
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
        cache: false    # 캐시를 남기지 않음(운영시에는 true)
        check-template-location: true   # templates 디렉토리에 파일이 있는지 없는지 체크. 없으면 에러 발생