server:
  port: 0 # random port

spring:
  application:
    name: sample-service

# config server actuator
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info
  health:
    mail:
      enabled: false

info:
  app:
    name: Sample Service
    description: 기본 템플릿
