// users
GET https://grandff-sample-spring-cloud-vw64pw99hp975-8000.githubpreview.dev/user/users?username=김정민

###

// users/{usersId}
GET https://grandff-sample-spring-cloud-vw64pw99hp975-8000.githubpreview.dev/user/users/1

###

// ping
GET https://grandff-sample-spring-cloud-vw64pw99hp975-8000.githubpreview.dev/sample-maven/ping

###

// 팀 생성
POST https://grandff-sample-spring-cloud-vw64pw99hp975-8000.githubpreview.dev/team/teams
Content-Type: application/json; charset=UTF-8

{
    "name": "맹구"    ,
    "address" : "영국"
}

###

// 팀멤버추가
POST https://grandff-sample-spring-cloud-vw64pw99hp975-8000.githubpreview.dev/team/1/teams
Content-Type: application/json; charset=UTF-8

{
    "name":"맹구"
}

###

// 사용자번호로 조회
GET https://grandff-sample-spring-cloud-vw64pw99hp975-8000.githubpreview.dev/team/1/teams



###

// member ping
GET https://grandff-sample-spring-cloud-vw64pw99hp975-8000.githubpreview.dev/member/ping

###

// user ping
GET https://grandff-sample-spring-cloud-vw64pw99hp975-8000.githubpreview.dev/user/ping

###

// order ping
GET https://grandff-sample-spring-cloud-vw64pw99hp975-8000.githubpreview.dev/order/ping

###

// delivery ping
GET https://grandff-sample-spring-cloud-vw64pw99hp975-8000.githubpreview.dev/delivery/ping


###

// user - order- delivery zipkin test
GET https://grandff-sample-spring-cloud-vw64pw99hp975-8000.githubpreview.dev/user/getorder/test/korea


###

// board - post check
//access-token: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0IiwiYXV0aG9yaXRpZXMiOiJBbGwiLCJleHAiOjE2NTY0Nzk5MzJ9.Suxa8ct-zHNX8qVQpwU75s_H8DxwzejtJFhuQ27oFgqhK_b5boMgNJ2KnWmmEmO39wsl4zSB8FqSOCo_7WYZ0A


###

// board - insert
// AUTHORIZATION에 로그인 후 리턴 받은 토큰을 넣어야함 
POST https://grandff-sample-spring-cloud-vw64pw99hp975-8000.githubpreview.dev/board/api/post/insert
Content-Type: application/json; charset=UTF-8
AUTHORIZATION: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0IiwiYXV0aG9yaXRpZXMiOiJBbGwiLCJleHAiOjE2NTY2NDA0NDF9.LkK8O7Hh4K_RSlQ16Ut948FN97E4g6iqnxFy8PcJoCJPOmY1Bm18PsuafunKiQWczRhlXVy36zXLBUBN0ZtkXw

{   
    "title" : "제목입니다5",
    "ctt" : "내용입니다5."
}

###

// board - insert authorization test
POST https://grandff-sample-spring-cloud-vw64pw99hp975-8000.githubpreview.dev/board/api/post/insert
Content-Type: application/json; charset=UTF-8

{   
    "title" : "제목입니다",
    "ctt" : "내용입니다."
}

###

// board - view
GET https://grandff-sample-spring-cloud-vw64pw99hp975-8000.githubpreview.dev/board/api/post/view

###

// board - list
GET https://grandff-sample-spring-cloud-vw64pw99hp975-8000.githubpreview.dev/board/api/post/list

###

// board - update
// AUTHORIZATION에 로그인 후 리턴 받은 토큰을 넣어야함 
// 동일한 아이디
POST https://grandff-sample-spring-cloud-vw64pw99hp975-8000.githubpreview.dev/board/api/post/update
Content-Type: application/json; charset=UTF-8
AUTHORIZATION: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0IiwiYXV0aG9yaXRpZXMiOiJBbGwiLCJleHAiOjE2NTY2NDA0NDF9.LkK8O7Hh4K_RSlQ16Ut948FN97E4g6iqnxFy8PcJoCJPOmY1Bm18PsuafunKiQWczRhlXVy36zXLBUBN0ZtkXw

{   
    "id" : 4,
    "title" : "제목입니다 수정입니다",
    "ctt" : "내용입니다 수정본입니다."
}

###

// board - update
// AUTHORIZATION에 로그인 후 리턴 받은 토큰을 넣어야함 
// 다른 아이디
POST https://grandff-sample-spring-cloud-vw64pw99hp975-8000.githubpreview.dev/board/api/post/insert
Content-Type: application/json; charset=UTF-8
AUTHORIZATION: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0IiwiYXV0aG9yaXRpZXMiOiJBbGwiLCJleHAiOjE2NTY2NDA0NDF9.LkK8O7Hh4K_RSlQ16Ut948FN97E4g6iqnxFy8PcJoCJPOmY1Bm18PsuafunKiQWczRhlXVy36zXLBUBN0ZtkXw

{   
    "title" : "제목입니다5",
    "ctt" : "내용입니다5."
}