// users
GET https://grandff-sample-spring-cloud-vw64pw99hp975-8000.githubpreview.dev/user/users?username=김정민

###

// users/{usersId}
GET https://grandff-sample-spring-cloud-vw64pw99hp975-8000.githubpreview.dev/user/users/1

###

// ping
GET https://grandff-sample-spring-cloud-vw64pw99hp975-8000.githubpreview.dev/user/ping

###

// 팀 생성
POST https://grandff-sample-spring-cloud-vw64pw99hp975-8000.githubpreview.dev/team/teams
Content-Type: application/json; charset=UTF-8

{
    "name": "맹구"    ,
    "address" : "영국"
}

###

// 팀멤버추가
POST https://grandff-sample-spring-cloud-vw64pw99hp975-8000.githubpreview.dev/team/1/teams
Content-Type: application/json; charset=UTF-8

{
    "name":"맹구"
}

###

// 사용자번호로 조회
GET https://grandff-sample-spring-cloud-vw64pw99hp975-8000.githubpreview.dev/team/1/teams



###

// member ping
GET https://grandff-sample-spring-cloud-vw64pw99hp975-8000.githubpreview.dev/member/ping