message:
  owner:  member-service-test
  content: member-service-test 입니다.


spring:
  application:
    name: member-service

  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      generate-ddl: true
      ddl-auto: create-drop
#      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000 # 1:N 관계를 해결하기 위해 필요
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2

  logging.level:
    org.hibernate.SQL: debug  