message:
  owner:  sample-service
  content: sample-service 입니다.

spring:
  datasource:
    url: dbUrl
    driver: com.h2.Driver
    username: admin
    password: password1234

jwt:
  token:
    key: secret_key