server :
  port : 0 # random port
  
spring :
  application :
    name : board-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
 
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}} # random port 사용시 eureka server에 인스턴스가 각각 표시되지 않는다
    preferIpAddress: true # 서비스간 통신 시 hostname 보다 ip 를 우선
  client:
    register-with-eureka: true # eureka 서버에 등록
    fetch-registry: true # 외부 검색 가능
    service-url:
      defaultZone: http://admin:admin@${eureka.instance.hostname:localhost}:8761/eureka
      
# config server actuator
management:
  endpoints:
    web:
      exposure:
        include: busrefresh, refresh, health, beans, info
  health:
    mail:
      enabled: false