// GET 서비스 상태 확인 
GET https://grandff-sample-spring-cloud-vw64pw99hp975-8000.githubpreview.dev/member/actuator/helath-info

###

// POST 서비스 상태 확인 
POST https://grandff-sample-spring-cloud-vw64pw99hp975-8000.githubpreview.dev/member/actuator/helath-info


###

// 회원가입
POST https://grandff-sample-spring-cloud-vw64pw99hp975-8000.githubpreview.dev/member/api/join
Content-Type: application/json; charset=UTF-8

{
    "userId" : "test",
    "userName" : "테스트",
    "password" : "cjswo123!",
    "tel" : "010-1111-2222",
    "email" : "dev@dev.com"
}